# Generated by Django 3.1.4 on 2023-02-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20230220_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Leads',
        ),
    ]
